//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_5.HobbyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HobbyServiceReference.IHobbyService")]
    public interface IHobbyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbyService/WordCharacters", ReplyAction="http://tempuri.org/IHobbyService/WordCharactersResponse")]
        string WordCharacters(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbyService/WordCharacters", ReplyAction="http://tempuri.org/IHobbyService/WordCharactersResponse")]
        System.Threading.Tasks.Task<string> WordCharactersAsync(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHobbyServiceChannel : assignment_5.HobbyServiceReference.IHobbyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HobbyServiceClient : System.ServiceModel.ClientBase<assignment_5.HobbyServiceReference.IHobbyService>, assignment_5.HobbyServiceReference.IHobbyService {
        
        public HobbyServiceClient() {
        }
        
        public HobbyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HobbyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HobbyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HobbyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WordCharacters(string word) {
            return base.Channel.WordCharacters(word);
        }
        
        public System.Threading.Tasks.Task<string> WordCharactersAsync(string word) {
            return base.Channel.WordCharactersAsync(word);
        }
    }
}
